  
name: Glitch Sync


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@master
      with:
        project-id: '${{ secrets.projectId }}'
        auth-token: '${{ secrets.authToken }}'
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Everything OK!
      
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Succes,
        echo the repository has been exported to glitch.
